import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "stockwise-language";
const THEME_STORAGE_KEY = "stockwise-theme";
const LANGUAGE_LOCALE_MAP = {
  pl: "pl-PL",
  en: "en-US",
  de: "de-DE",
};

const TRANSLATIONS = {
  pl: {
    shell: {
      eyebrow: "Warehouse Flow",
      brand: "StockWise",
      themeLight: "Light",
      themeDark: "Dark",
      languageLabel: "Jezyk",
      themeLabel: "Motyw",
      back: "Powrot",
    },
    common: {
      warehouse: "Magazyn",
      loading: "Ladowanie...",
      cancel: "Anuluj",
      close: "Zamknij",
      save: "Zapisz",
      actions: "Akcje",
      search: "Szukaj",
      import: "Import",
      export: "Eksport",
      add: "Dodaj",
      edit: "Edytuj",
      delete: "Usun",
      allSku: "Wszystkie SKU",
      allLocations: "Wszystkie lokalizacje",
      noData: "Brak danych",
      previous: "Poprzednia",
      next: "Nastepna",
      openSection: "Otworz sekcje",
      backToMenu: "Powrot do menu",
    },
    menu: {
      greeting: "Czesc, {{name}}",
      subtitle: "Wybierz obszar pracy i przejdz od razu do potrzebnego modulu.",
      quickStart: "Szybki start",
      logout: "Wyloguj",
      logoutLoading: "Wylogowuje...",
      workspace: "Twoj panel roboczy",
      role: "Rola",
      noAssignedWarehouse: "Brak przypisanego magazynu",
      process: "Proces",
      history: "Historia",
      data: "Dane",
      dashboard: "Statystyki",
      settings: "Ustawienia",
      processDesc: "Operacje terenowe, skanowanie i sesje pracy",
      historyDesc: "Wyniki inwentaryzacji i przeglad operacji",
      dataDesc: "Referencje, importy i historia zmian",
      dashboardDesc: "Metryki, tempo pracy i dane finansowe",
      settingsDesc: "Panel administracyjny, konfiguracja i statusy",
      qrTitle: "QR do logowania na telefonie",
      qrDescription:
        "Zeskanuj ten kod z dowolnego komputera albo monitora, aby szybko otworzyc ekran logowania StockWise na telefonie operatora.",
      loginLink: "Link do logowania:",
      qrHint:
        "Jesli operator pracuje na innym urzadzeniu, wystarczy zeskanowac QR i zalogowac sie standardowo.",
      quickStartTitle: "Szybki start gap inventory",
      quickStartSubtitle:
        "Zeskanuj najblizsza lokalizacje, a system dobierze najlepszy kierunek rozpoczecia kontroli.",
      startLocation: "Lokalizacja startowa",
      startLocationHint:
        "Moze to byc dowolna lokalizacja z mapy magazynu w poblizu miejsca, od ktorego operator chce ruszyc.",
      scanLocation: "Skan lokalizacji",
      locationPlaceholder: "Np. A.01.001.D.3",
      runQuickStart: "Uruchom szybki start",
      scanLocationAria: "Otworz skaner lokalizacji dla szybkiego startu",
      scanModalTitle: "Skanuj lokalizacje startowa",
      scanModalDescription:
        "Zeskanuj kod lokalizacji aparatem telefonu albo wgraj zdjecie, aby od razu uruchomic szybki start pustych lokalizacji.",
      quickStartError: "Zeskanuj lub wpisz lokalizacje, od ktorej chcesz zaczac.",
      quickStartInitError: "Nie udalo sie uruchomic szybkiego startu.",
      sessionLogoutMessage: "Zamykam sesje i wylogowuje operatora ze StockWise...",
    },
    auth: {
      brandSubtitle: "Warehouse operations, calmer, cleaner, clearer.",
      site: "Magazyn",
      chooseSite: "Wybierz magazyn",
      login: "Login",
      loginPlaceholder: "Wpisz login",
      password: "Haslo",
      passwordPlaceholder: "Wpisz haslo",
      signIn: "Zaloguj sie",
      signInLoading: "Logowanie...",
      enterLogin: "Wprowadz login",
      enterPassword: "Wprowadz haslo",
      selectSite: "Wybierz magazyn",
      loginError: "Blad logowania",
      systemError: "Blad systemu",
    },
    loaders: {
      protectedRoute: "Sprawdzam dostep i przygotowuje widok...",
      roleRoute: "Sprawdzam uprawnienia i konfiguracje widoku...",
    },
    processStart: {
      title: "Wybierz tryb pracy",
      subtitle: "Rozpocznij proces, ktory najlepiej odpowiada Twojemu zadaniu na hali.",
      emptyTitle: "Inwentaryzuj puste",
      emptyDesc: "Kontrola pustych lokalizacji, potwierdzenia, nadwyzki i zgloszenia problemow.",
      manualTitle: "Inwentaryzacja reczna",
      manualDesc: "Reczne skanowanie lokalizacji, SKU, LOT i zapisy brakow oraz nadwyzek.",
      start: "Rozpocznij prace",
      startLoading: "Uruchamiam proces...",
      overlay: "Uruchamiam sesje operatora i przygotowuje wybrany proces...",
    },
    dataMenu: {
      title: "Dane referencyjne",
      subtitle: "Centralne miejsce do zarzadzania produktami, stockiem, cenami i historia zmian.",
      productsTitle: "Produkty",
      productsDesc: "Referencje SKU, EAN i statusy indeksow.",
      stockTitle: "Stock",
      stockDesc: "Stany magazynowe po lokalizacji i produkcie.",
      pricesTitle: "Ceny",
      pricesDesc: "Wartosci produktow wykorzystywane w analizach finansowych.",
      locationsTitle: "Mapa magazynu",
      locationsDesc: "Struktura lokalizacji, stref i statusow operacyjnych.",
      correctionsTitle: "Historia korekt",
      correctionsDesc: "Zmiany danych i log korekt bez zgloszen operacyjnych.",
      problemsTitle: "Problemy",
      problemsDesc: "Zgloszenia z procesow inwentaryzacji i blokady lokalizacji do zwolnienia.",
    },
    settings: {
      title: "Ustawienia",
      subtitle: "Wybierz obszar administracyjny, nad ktorym chcesz dalej pracowac.",
      usersTitle: "Uzytkownicy",
      usersDesc: "Zarzadzanie kontami, rolami i dostepem operatorow do systemu.",
      processTitle: "Konfiguracja procesu",
      processDesc: "Przeglad krokow procesu, wymaganych pol i logiki skanowania.",
      scanningTitle: "Skanowanie",
      scanningDesc: "Wlaczanie kamery, wybor pol procesu i formatow kodow dla telefonow operatorow.",
      importExportTitle: "Import/Export",
      importExportDesc: "Skroty do obslugi danych wsadowych, eksportow i konfiguracji zasilek.",
      logsTitle: "Logi",
      logsDesc: "Punkt startowy do audytow, historii zmian i logow operacyjnych.",
      statusesTitle: "Statusy",
      statusesDesc: "Biezacy status systemu oraz szybki przeglad kondycji srodowiska.",
    },
    dataTable: {
      subtitle: "Jednolity widok roboczy do filtrowania, przegladu i utrzymania danych.",
      searchPlaceholder: "Szukaj...",
      searchAria: "Wyszukaj",
      shownRecords: "Pokazywane: {{shown}} z {{total}} rekordow",
      shownPageRecords: "Pokazywane: {{shown}} rekordow na tej stronie",
      pageStatus: "Strona {{current}} / {{total}}",
      pageStatusSimple: "Strona {{current}}",
    },
    dashboard: {
      kicker: "Panel statystyk",
      title: "Dashboard statystyk",
      subtitle: "Podsumowanie pracy operacyjnej, finansowej i sesyjnej dla wybranego okresu.",
      refresh: "Odswiez",
      export: "Eksport CSV",
      exporting: "Eksport...",
      year: "Rok",
      month: "Miesiac",
      allMonths: "Wszystkie miesiace",
      source: "Zrodlo danych",
      sourceRpc: "backend RPC",
      sourceFallback: "frontend fallback",
      loading: "Pobieram statystyki...",
      loadError: "Nie udalo sie pobrac statystyk",
      exportError: "Nie udalo sie wyeksportowac statystyk",
      checkedLocations: "Sprawdzone lokalizacje",
      checkedLocationsHint: "Liczba unikalnych lokalizacji z wpisami w okresie",
      operationsCount: "Liczba operacji",
      shortagesCount: "Braki",
      surplusesCount: "Nadwyzki",
      problemsCount: "Zgloszone problemy",
      surplusValue: "Wartosc nadwyzek",
      shortageValue: "Wartosc brakow",
      totalDifferenceValue: "Laczna wartosc roznic",
      avgLocationControl: "Sredni czas kontroli lokalizacji",
      locationsPerHour: "Lokalizacje na godzine",
      avgOperationsPerSession: "Srednia operacji na sesje",
      sessionsCount: "Liczba sesji",
      avgSession: "Sredni czas sesji",
      longestSession: "Najdluzsza sesja",
      zoneStatsTitle: "Statystyki per strefa",
      zoneStatsSubtitle: "Rozbicie wynikow na strefy magazynowe dla aktualnie wybranego okresu.",
      noData: "Brak danych dla wybranego okresu.",
      metric: "Metryka",
      value: "Wartosc",
      zone: "Strefa",
      zoneHealthEyebrow: "Zdrowie strefy",
      zoneTotalLocations: "Liczba lokalizacji",
      zoneTotalLocationsHint: "{{share}}% calej mapy magazynu",
      zoneDoneLocations: "Lokalizacje done",
      zoneDoneLocationsHint: "Zamkniete i czyste pozycje",
      zonePendingActive: "Pending / active",
      zonePendingActiveHint: "Wciaz w toku albo czekaja na domkniecie",
      zoneProblemsHint: "Otwarte blokery operacyjne w tej strefie",
      zoneCheckedLocations: "Sprawdzone lokalizacje",
      zoneOperations: "Operacje",
      zoneDifferenceValue: "Wartosc roznic",
      zoneShareSuffix: "udzialu",
      zoneIssueCount: "problemow",
      zoneLegendTitle: "Legenda zdrowia stref",
      zoneLegendSubtitle: "Kolor pokazuje kondycje strefy, a rozmiar kafla jej udzial w mapie magazynu.",
      zoneLegendClear: "Clear: done dominuje, praktycznie brak problemow.",
      zoneLegendStable: "Stable: strefa zdrowa, ale jeszcze nie idealna.",
      zoneLegendWatch: "Watchlist: potrzeba uwagi, bo rosnie liczba otwartych pozycji.",
      zoneLegendCritical: "Critical: obszar wymaga reakcji teraz.",
      zoneTopRiskTitle: "Top 3 strefy wymagajace uwagi",
      zoneTopRiskSubtitle: "Najslabsze health score w wybranym okresie.",
      zoneTopRiskImpact: "lokacji · {{issues}} problemow",
      healthClear: "Clear",
      healthStable: "Stabilna",
      healthWatch: "Obserwuj",
      healthCritical: "Krytyczna",
      healthClearSummary: "Strefa jest pod kontrola: lokalizacje done dominuja i nie ma istotnych problemow.",
      healthStableSummary: "Strefa wyglada zdrowo, ale wciaz wymaga niewielkiego follow-upu operacyjnego.",
      healthWatchSummary: "Strefa jest mieszana: niedomkniete lokalizacje albo liczba problemow zaczyna sciagac wynik w dol.",
      healthCriticalSummary: "Strefa wymaga uwagi teraz: zbyt duzo otwartych lokalizacji albo problemow operacyjnych.",
      healthEmptySummary: "W tej strefie nie ma jeszcze zmapowanych lokalizacji.",
    },
    roles: {
      user: "Operator",
      superuser: "Superuser",
      office: "Office",
      manager: "Manager",
      admin: "Administrator",
      missing: "Brak",
    },
  },
  en: {
    shell: {
      eyebrow: "Warehouse Flow",
      brand: "StockWise",
      themeLight: "Light",
      themeDark: "Dark",
      languageLabel: "Language",
      themeLabel: "Theme",
      back: "Back",
    },
    common: {
      warehouse: "Warehouse",
      loading: "Loading...",
      cancel: "Cancel",
      close: "Close",
      save: "Save",
      actions: "Actions",
      search: "Search",
      import: "Import",
      export: "Export",
      add: "Add",
      edit: "Edit",
      delete: "Delete",
      allSku: "All SKUs",
      allLocations: "All locations",
      noData: "No data",
      previous: "Previous",
      next: "Next",
      openSection: "Open section",
      backToMenu: "Back to menu",
    },
    menu: {
      greeting: "Hello, {{name}}",
      subtitle: "Choose your work area and jump straight into the module you need.",
      quickStart: "Quick start",
      logout: "Log out",
      logoutLoading: "Logging out...",
      workspace: "Your workspace",
      role: "Role",
      noAssignedWarehouse: "No warehouse assigned",
      process: "Process",
      history: "History",
      data: "Data",
      dashboard: "Statistics",
      settings: "Settings",
      processDesc: "Field operations, scanning and work sessions",
      historyDesc: "Inventory results and operation review",
      dataDesc: "References, imports and change history",
      dashboardDesc: "Metrics, pace of work and financial data",
      settingsDesc: "Admin panel, configuration and statuses",
      qrTitle: "Phone login QR",
      qrDescription:
        "Scan this code from any computer or monitor to quickly open the StockWise login screen on the operator phone.",
      loginLink: "Login link:",
      qrHint:
        "If the operator works on another device, just scan the QR code and log in normally.",
      quickStartTitle: "Quick start gap inventory",
      quickStartSubtitle:
        "Scan the nearest location and the system will choose the best direction to begin the check.",
      startLocation: "Starting location",
      startLocationHint:
        "It can be any location from the warehouse map near the area where the operator wants to begin.",
      scanLocation: "Location scan",
      locationPlaceholder: "e.g. A.01.001.D.3",
      runQuickStart: "Run quick start",
      scanLocationAria: "Open location scanner for quick start",
      scanModalTitle: "Scan starting location",
      scanModalDescription:
        "Scan the location code with the phone camera or upload a photo to start empty-location control immediately.",
      quickStartError: "Scan or enter the location where you want to begin.",
      quickStartInitError: "Could not start quick start.",
      sessionLogoutMessage: "Closing the session and logging the operator out of StockWise...",
    },
    auth: {
      brandSubtitle: "Warehouse operations, calmer, cleaner, clearer.",
      site: "Warehouse",
      chooseSite: "Choose warehouse",
      login: "Login",
      loginPlaceholder: "Enter login",
      password: "Password",
      passwordPlaceholder: "Enter password",
      signIn: "Sign in",
      signInLoading: "Signing in...",
      enterLogin: "Enter login",
      enterPassword: "Enter password",
      selectSite: "Choose warehouse",
      loginError: "Login failed",
      systemError: "System error",
    },
    loaders: {
      protectedRoute: "Checking access and preparing the view...",
      roleRoute: "Checking permissions and view configuration...",
    },
    processStart: {
      title: "Choose work mode",
      subtitle: "Start the process that best matches the task you need to do on the floor.",
      emptyTitle: "Empty location count",
      emptyDesc: "Check empty locations, confirm them, report surpluses and raise issues.",
      manualTitle: "Manual inventory",
      manualDesc: "Manual scanning of location, SKU, LOT and recording shortages or surpluses.",
      start: "Start work",
      startLoading: "Starting process...",
      overlay: "Starting operator session and preparing the selected process...",
    },
    dataMenu: {
      title: "Reference data",
      subtitle: "Central place to manage products, stock, prices and change history.",
      productsTitle: "Products",
      productsDesc: "SKU, EAN and item status references.",
      stockTitle: "Stock",
      stockDesc: "Warehouse stock by location and product.",
      pricesTitle: "Prices",
      pricesDesc: "Product values used in financial analysis.",
      locationsTitle: "Warehouse map",
      locationsDesc: "Location structure, zones and operational statuses.",
      correctionsTitle: "Correction history",
      correctionsDesc: "Data changes and correction log without operational issues.",
      problemsTitle: "Problems",
      problemsDesc: "Inventory process issues and blocked locations waiting to be released.",
    },
    settings: {
      title: "Settings",
      subtitle: "Choose the administrative area you want to work on next.",
      usersTitle: "Users",
      usersDesc: "Manage accounts, roles and operator access to the system.",
      processTitle: "Process configuration",
      processDesc: "Overview of process steps, required fields and scanning logic.",
      scanningTitle: "Scanning",
      scanningDesc: "Camera settings, process fields and code formats for operator phones.",
      importExportTitle: "Import/Export",
      importExportDesc: "Shortcuts for batch data, exports and feed configuration.",
      logsTitle: "Logs",
      logsDesc: "Starting point for audits, change history and operational logs.",
      statusesTitle: "Statuses",
      statusesDesc: "Current system status and quick health overview of the environment.",
    },
    dataTable: {
      subtitle: "Unified work view for filtering, reviewing and maintaining data.",
      searchPlaceholder: "Search...",
      searchAria: "Search",
      shownRecords: "Showing: {{shown}} of {{total}} records",
      shownPageRecords: "Showing: {{shown}} records on this page",
      pageStatus: "Page {{current}} / {{total}}",
      pageStatusSimple: "Page {{current}}",
    },
    dashboard: {
      kicker: "Statistics panel",
      title: "Statistics dashboard",
      subtitle: "Summary of operational, financial and session work for the selected period.",
      refresh: "Refresh",
      export: "Export CSV",
      exporting: "Exporting...",
      year: "Year",
      month: "Month",
      allMonths: "All months",
      source: "Data source",
      sourceRpc: "backend RPC",
      sourceFallback: "frontend fallback",
      loading: "Loading statistics...",
      loadError: "Could not load statistics",
      exportError: "Could not export statistics",
      checkedLocations: "Checked locations",
      checkedLocationsHint: "Number of unique locations with entries in the selected period",
      operationsCount: "Operations count",
      shortagesCount: "Shortages",
      surplusesCount: "Surpluses",
      problemsCount: "Reported issues",
      surplusValue: "Surplus value",
      shortageValue: "Shortage value",
      totalDifferenceValue: "Total difference value",
      avgLocationControl: "Average location control time",
      locationsPerHour: "Locations per hour",
      avgOperationsPerSession: "Average operations per session",
      sessionsCount: "Sessions count",
      avgSession: "Average session time",
      longestSession: "Longest session",
      zoneStatsTitle: "Zone statistics",
      zoneStatsSubtitle: "Breakdown of results by warehouse zones for the currently selected period.",
      noData: "No data for the selected period.",
      metric: "Metric",
      value: "Value",
      zone: "Zone",
      zoneHealthEyebrow: "Zone health",
      zoneTotalLocations: "Total locations",
      zoneTotalLocationsHint: "{{share}}% of the mapped warehouse",
      zoneDoneLocations: "Done locations",
      zoneDoneLocationsHint: "Completed and clean positions",
      zonePendingActive: "Pending / active",
      zonePendingActiveHint: "Still in flow or waiting for closure",
      zoneProblemsHint: "Open operational blockers in this zone",
      zoneCheckedLocations: "Checked locations",
      zoneOperations: "Operations",
      zoneDifferenceValue: "Difference value",
      zoneShareSuffix: "share",
      zoneIssueCount: "issues",
      zoneLegendTitle: "Zone health legend",
      zoneLegendSubtitle: "Color shows zone condition, tile size shows its share of the warehouse map.",
      zoneLegendClear: "Clear: done dominates and there are almost no issues.",
      zoneLegendStable: "Stable: healthy zone, but not perfect yet.",
      zoneLegendWatch: "Watchlist: needs attention because open positions are growing.",
      zoneLegendCritical: "Critical: area needs action now.",
      zoneTopRiskTitle: "Top 3 zones that need attention",
      zoneTopRiskSubtitle: "Lowest health scores in the selected period.",
      zoneTopRiskImpact: "{{locations}} locations · {{issues}} issues",
      healthClear: "Clear",
      healthStable: "Stable",
      healthWatch: "Watchlist",
      healthCritical: "Critical",
      healthClearSummary: "Zone is under control: done locations dominate and there are no meaningful issues.",
      healthStableSummary: "Zone looks healthy, but it still needs a bit of operational follow-up.",
      healthWatchSummary: "Zone is mixed: unfinished locations or issue load starts to drag health down.",
      healthCriticalSummary: "Zone needs attention now: too many open locations or operational issues.",
      healthEmptySummary: "No mapped locations in this zone yet.",
    },
    roles: {
      user: "Operator",
      superuser: "Superuser",
      office: "Office",
      manager: "Manager",
      admin: "Administrator",
      missing: "Missing",
    },
  },
  de: {
    shell: {
      eyebrow: "Warehouse Flow",
      brand: "StockWise",
      themeLight: "Hell",
      themeDark: "Dunkel",
      languageLabel: "Sprache",
      themeLabel: "Modus",
      back: "Zuruck",
    },
    common: {
      warehouse: "Lager",
      loading: "Laden...",
      cancel: "Abbrechen",
      close: "Schliessen",
      save: "Speichern",
      actions: "Aktionen",
      search: "Suchen",
      import: "Import",
      export: "Export",
      add: "Hinzufugen",
      edit: "Bearbeiten",
      delete: "Loschen",
      allSku: "Alle SKU",
      allLocations: "Alle Lokationen",
      noData: "Keine Daten",
      previous: "Zuruck",
      next: "Weiter",
      openSection: "Bereich offnen",
      backToMenu: "Zuruck zum Menu",
    },
    menu: {
      greeting: "Hallo, {{name}}",
      subtitle: "Wahle deinen Arbeitsbereich und gehe direkt in das passende Modul.",
      quickStart: "Schnellstart",
      logout: "Abmelden",
      logoutLoading: "Abmeldung...",
      workspace: "Dein Arbeitsbereich",
      role: "Rolle",
      noAssignedWarehouse: "Kein Lager zugewiesen",
      process: "Prozess",
      history: "Historie",
      data: "Daten",
      dashboard: "Statistiken",
      settings: "Einstellungen",
      processDesc: "Feldoperationen, Scannen und Arbeitssitzungen",
      historyDesc: "Inventurergebnisse und Vorgangsubersicht",
      dataDesc: "Stammdaten, Importe und Anderungshistorie",
      dashboardDesc: "Metriken, Arbeitstempo und Finanzdaten",
      settingsDesc: "Adminbereich, Konfiguration und Status",
      qrTitle: "QR fur Login am Telefon",
      qrDescription:
        "Scanne diesen Code von einem beliebigen Computer oder Monitor, um den StockWise-Login auf dem Operator-Handy schnell zu offnen.",
      loginLink: "Login-Link:",
      qrHint:
        "Wenn der Operator auf einem anderen Gerat arbeitet, reicht es, den QR-Code zu scannen und sich normal anzumelden.",
      quickStartTitle: "Schnellstart Gap Inventory",
      quickStartSubtitle:
        "Scanne die nachste Lokation und das System wählt die beste Richtung fur den Start der Kontrolle.",
      startLocation: "Startlokation",
      startLocationHint:
        "Das kann jede Lokation aus der Lagerkarte in der Nahe des Startbereichs des Operators sein.",
      scanLocation: "Lokationsscan",
      locationPlaceholder: "z. B. A.01.001.D.3",
      runQuickStart: "Schnellstart ausfuhren",
      scanLocationAria: "Lokationsscanner fur Schnellstart offnen",
      scanModalTitle: "Startlokation scannen",
      scanModalDescription:
        "Scanne den Lokationscode mit der Kamera oder lade ein Foto hoch, um die Kontrolle leerer Lokationen sofort zu starten.",
      quickStartError: "Scanne oder gib die Lokation ein, an der du beginnen willst.",
      quickStartInitError: "Schnellstart konnte nicht gestartet werden.",
      sessionLogoutMessage: "Sitzung wird beendet und der Operator wird aus StockWise abgemeldet...",
    },
    auth: {
      brandSubtitle: "Warehouse operations, calmer, cleaner, clearer.",
      site: "Lager",
      chooseSite: "Lager auswahlen",
      login: "Login",
      loginPlaceholder: "Login eingeben",
      password: "Passwort",
      passwordPlaceholder: "Passwort eingeben",
      signIn: "Anmelden",
      signInLoading: "Anmeldung...",
      enterLogin: "Login eingeben",
      enterPassword: "Passwort eingeben",
      selectSite: "Lager auswahlen",
      loginError: "Anmeldung fehlgeschlagen",
      systemError: "Systemfehler",
    },
    loaders: {
      protectedRoute: "Zugriff wird gepruft und Ansicht vorbereitet...",
      roleRoute: "Berechtigungen und Ansichts-Konfiguration werden gepruft...",
    },
    processStart: {
      title: "Arbeitsmodus wahlen",
      subtitle: "Starte den Prozess, der am besten zu deiner Aufgabe auf der Flache passt.",
      emptyTitle: "Leere Lokationen prufen",
      emptyDesc: "Kontrolle leerer Lokationen, Bestatigung, Mehrmengen und Problem-Meldungen.",
      manualTitle: "Manuelle Inventur",
      manualDesc: "Manuelles Scannen von Lokation, SKU, LOT und Erfassung von Fehl- oder Mehrmengen.",
      start: "Arbeit starten",
      startLoading: "Prozess startet...",
      overlay: "Operatorsitzung wird gestartet und der gewahlte Prozess wird vorbereitet...",
    },
    dataMenu: {
      title: "Referenzdaten",
      subtitle: "Zentrale Stelle zur Verwaltung von Produkten, Bestand, Preisen und Anderungshistorie.",
      productsTitle: "Produkte",
      productsDesc: "Referenzen fur SKU, EAN und Artikelstatus.",
      stockTitle: "Bestand",
      stockDesc: "Lagerbestande nach Lokation und Produkt.",
      pricesTitle: "Preise",
      pricesDesc: "Produktwerte fur finanzielle Auswertungen.",
      locationsTitle: "Lagerkarte",
      locationsDesc: "Struktur der Lokationen, Zonen und operativen Status.",
      correctionsTitle: "Korrekturhistorie",
      correctionsDesc: "Datenanderungen und Korrekturlog ohne operative Meldungen.",
      problemsTitle: "Probleme",
      problemsDesc: "Meldungen aus Inventurprozessen und blockierte Lokationen zur Freigabe.",
    },
    settings: {
      title: "Einstellungen",
      subtitle: "Wahle den Administrationsbereich, an dem du weiterarbeiten mochtest.",
      usersTitle: "Benutzer",
      usersDesc: "Verwaltung von Konten, Rollen und Operator-Zugriffen auf das System.",
      processTitle: "Prozesskonfiguration",
      processDesc: "Uberblick uber Prozessschritte, Pflichtfelder und Scanlogik.",
      scanningTitle: "Scannen",
      scanningDesc: "Kameraeinstellungen, Prozessfelder und Codeformate fur Operator-Handys.",
      importExportTitle: "Import/Export",
      importExportDesc: "Schnellzugriffe fur Massendaten, Exporte und Feed-Konfiguration.",
      logsTitle: "Logs",
      logsDesc: "Startpunkt fur Audits, Anderungshistorie und operative Logs.",
      statusesTitle: "Status",
      statusesDesc: "Aktueller Systemstatus und schneller Gesundheitscheck der Umgebung.",
    },
    dataTable: {
      subtitle: "Einheitliche Arbeitsansicht zum Filtern, Prufen und Pflegen von Daten.",
      searchPlaceholder: "Suchen...",
      searchAria: "Suchen",
      shownRecords: "Angezeigt: {{shown}} von {{total}} Eintragen",
      shownPageRecords: "Angezeigt: {{shown}} Eintrage auf dieser Seite",
      pageStatus: "Seite {{current}} / {{total}}",
      pageStatusSimple: "Seite {{current}}",
    },
    dashboard: {
      kicker: "Statistikbereich",
      title: "Statistik-Dashboard",
      subtitle: "Zusammenfassung der operativen, finanziellen und sitzungsbezogenen Arbeit fur den gewahlten Zeitraum.",
      refresh: "Aktualisieren",
      export: "CSV exportieren",
      exporting: "Export lauft...",
      year: "Jahr",
      month: "Monat",
      allMonths: "Alle Monate",
      source: "Datenquelle",
      sourceRpc: "Backend-RPC",
      sourceFallback: "Frontend-Fallback",
      loading: "Statistiken werden geladen...",
      loadError: "Statistiken konnten nicht geladen werden",
      exportError: "Statistiken konnten nicht exportiert werden",
      checkedLocations: "Geprufte Lokationen",
      checkedLocationsHint: "Anzahl eindeutiger Lokationen mit Eintragen im ausgewahlten Zeitraum",
      operationsCount: "Anzahl Operationen",
      shortagesCount: "Fehlmengen",
      surplusesCount: "Mehrmengen",
      problemsCount: "Gemeldete Probleme",
      surplusValue: "Wert der Mehrmengen",
      shortageValue: "Wert der Fehlmengen",
      totalDifferenceValue: "Gesamtwert der Differenzen",
      avgLocationControl: "Durchschnittliche Kontrollzeit pro Lokation",
      locationsPerHour: "Lokationen pro Stunde",
      avgOperationsPerSession: "Durchschnittliche Operationen pro Sitzung",
      sessionsCount: "Anzahl Sitzungen",
      avgSession: "Durchschnittliche Sitzungsdauer",
      longestSession: "Langste Sitzung",
      zoneStatsTitle: "Zonenstatistik",
      zoneStatsSubtitle: "Aufschlüsselung der Ergebnisse nach Lagerzonen fur den aktuell gewahlten Zeitraum.",
      noData: "Keine Daten fur den gewahlten Zeitraum.",
      metric: "Kennzahl",
      value: "Wert",
      zone: "Zone",
      zoneHealthEyebrow: "Zonengesundheit",
      zoneTotalLocations: "Anzahl Lokationen",
      zoneTotalLocationsHint: "{{share}}% der gesamten Lagerkarte",
      zoneDoneLocations: "Done-Lokationen",
      zoneDoneLocationsHint: "Abgeschlossene und saubere Positionen",
      zonePendingActive: "Pending / active",
      zonePendingActiveHint: "Noch im Flow oder wartet auf Abschluss",
      zoneProblemsHint: "Offene operative Blocker in dieser Zone",
      zoneCheckedLocations: "Geprufte Lokationen",
      zoneOperations: "Operationen",
      zoneDifferenceValue: "Differenzwert",
      zoneShareSuffix: "Anteil",
      zoneIssueCount: "Probleme",
      zoneLegendTitle: "Legende der Zonengesundheit",
      zoneLegendSubtitle: "Die Farbe zeigt den Zustand der Zone, die Kachelgrosse ihren Anteil an der Lagerkarte.",
      zoneLegendClear: "Klar: done dominiert und es gibt fast keine Probleme.",
      zoneLegendStable: "Stabil: gesunde Zone, aber noch nicht perfekt.",
      zoneLegendWatch: "Beobachten: braucht Aufmerksamkeit, weil offene Positionen zunehmen.",
      zoneLegendCritical: "Kritisch: Bereich braucht jetzt Aktion.",
      zoneTopRiskTitle: "Top 3 Zonen mit Handlungsbedarf",
      zoneTopRiskSubtitle: "Niedrigste Health Scores im gewahlten Zeitraum.",
      zoneTopRiskImpact: "{{locations}} Lokationen · {{issues}} Probleme",
      healthClear: "Klar",
      healthStable: "Stabil",
      healthWatch: "Beobachten",
      healthCritical: "Kritisch",
      healthClearSummary: "Die Zone ist unter Kontrolle: Done-Lokationen dominieren und es gibt keine wesentlichen Probleme.",
      healthStableSummary: "Die Zone wirkt gesund, braucht aber noch etwas operatives Follow-up.",
      healthWatchSummary: "Die Zone ist gemischt: offene Lokationen oder Problemvolumen ziehen den Gesundheitswert nach unten.",
      healthCriticalSummary: "Die Zone braucht jetzt Aufmerksamkeit: zu viele offene Lokationen oder operative Probleme.",
      healthEmptySummary: "In dieser Zone sind noch keine Lokationen hinterlegt.",
    },
    roles: {
      user: "Operator",
      superuser: "Superuser",
      office: "Office",
      manager: "Manager",
      admin: "Administrator",
      missing: "Fehlt",
    },
  },
};

const DEFAULT_LANGUAGE = "pl";
const DEFAULT_THEME = "light";
const LANGUAGES = [
  { value: "pl", label: "PL" },
  { value: "en", label: "EN" },
  { value: "de", label: "DE" },
];

const AppPreferencesContext = createContext(null);

function normalizeLanguage(value) {
  return LANGUAGES.some((item) => item.value === value) ? value : DEFAULT_LANGUAGE;
}

function normalizeTheme(value) {
  return value === "dark" ? "dark" : DEFAULT_THEME;
}

function readStoredPreference(key, fallback) {
  if (typeof window === "undefined") {
    return fallback;
  }

  return window.localStorage.getItem(key) || fallback;
}

function resolveTranslation(language, key) {
  const source = TRANSLATIONS[language] || TRANSLATIONS[DEFAULT_LANGUAGE];
  return String(key || "")
    .split(".")
    .reduce((accumulator, segment) => (accumulator && accumulator[segment] !== undefined ? accumulator[segment] : null), source);
}

function interpolate(template, variables) {
  return String(template || "").replace(/\{\{(.*?)\}\}/g, (_, key) => {
    const normalizedKey = String(key || "").trim();
    return variables?.[normalizedKey] ?? "";
  });
}

export function AppPreferencesProvider({ children }) {
  const [language, setLanguageState] = useState(() =>
    normalizeLanguage(readStoredPreference(LANGUAGE_STORAGE_KEY, DEFAULT_LANGUAGE))
  );
  const [theme, setThemeState] = useState(() =>
    normalizeTheme(readStoredPreference(THEME_STORAGE_KEY, DEFAULT_THEME))
  );

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    window.localStorage.setItem(THEME_STORAGE_KEY, theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo(() => {
    function t(key, variables = {}) {
      const direct = resolveTranslation(language, key);
      const fallback = resolveTranslation(DEFAULT_LANGUAGE, key);
      return interpolate(direct ?? fallback ?? key, variables);
    }

    return {
      language,
      setLanguage: (nextLanguage) => setLanguageState(normalizeLanguage(nextLanguage)),
      locale: LANGUAGE_LOCALE_MAP[language] || LANGUAGE_LOCALE_MAP[DEFAULT_LANGUAGE],
      theme,
      setTheme: (nextTheme) => setThemeState(normalizeTheme(nextTheme)),
      toggleTheme: () => setThemeState((current) => (current === "dark" ? "light" : "dark")),
      t,
      languages: LANGUAGES,
    };
  }, [language, theme]);

  return <AppPreferencesContext.Provider value={value}>{children}</AppPreferencesContext.Provider>;
}

export function useAppPreferences() {
  const context = useContext(AppPreferencesContext);

  if (!context) {
    throw new Error("useAppPreferences must be used inside AppPreferencesProvider");
  }

  return context;
}

export function getLanguageLocale(language) {
  return LANGUAGE_LOCALE_MAP[normalizeLanguage(language)] || LANGUAGE_LOCALE_MAP[DEFAULT_LANGUAGE];
}

export function getStoredLanguage() {
  return normalizeLanguage(readStoredPreference(LANGUAGE_STORAGE_KEY, DEFAULT_LANGUAGE));
}
